### PR TITLE
Add user to memcached command

### PR DESCRIPTION
**Pull request by philipseidel**
The current memcached command fails if run as root on CentOS 7.  Add memcached user in order to start the server.

### CODE REVIEW

**Comment by dridi** [comment]
Should fix #18

**Comment by dmatetelki** [comment]
I still get the same(?) error on centos7 as @ingvarha: https://filebin.net/wf89cb02qopx2fmv/crash.txt

**Comment by dridi** [comment]
Then no, not fixing that :(

Can you get a stab at this panic?

**Comment by dmatetelki** [comment]
@Dridi : sure. I'll exercise my negging powers

**Comment by dmatetelki** [comment]
@Dridi : Seems to me that the problem is with init:

```
**** v1    0.4 vsl|          0 Debug           - memcached pool config '--SERVER=localhost: --BINARY-PROTOCOL --POOL-MAX=40'
**** v1    0.4 vsl|          0 Error           - memcached servers() error
**** v1    0.4 vsl|          0 Error           - ERROR OCCURED WHILE PARSING
```

is lacking a port. In `gen-vcl.sh` the port detection fails: 

`PORT="$(lsof -a -F -i4 -p "$PID" | awk -F: '/^n/ {print $2}')"`

**Comment by dmatetelki** [comment]
because i did not have memcached installed and configure only check libmemcached :P

**Comment by dmatetelki** [comment]
Having `memcached` installed (not just the required and checked `libmemcached`) fixes #18, i did not needed the  `-u memcached` fix on centos7

**Comment by dmatetelki** [comment]
Ok, i see. To run `memcached` as root, we need to pass the user with `-u`. I'm ok with the patch.

**Comment by dridi** [comment]
What happens if we're not running as root and can't `setuid` to `memcached`?

**Comment by dmatetelki** [comment]
@Dridi : if the user is not root, the passed `-u username` is disregarded:

https://github.com/memcached/memcached/blob/master/memcached.c#L7529-L7547

**Comment by dridi** [comment]
Good, what if we're running as `root` and don't have a `memcached` user? Shouldn't we use `nobody` instead for the test suite?

**Comment by dmatetelki** [comment]
@philipseidel : what is your opinion on using user `nobody` when running the tests as `root`?

**Comment by philipseidel** [comment]
@dmatetelki that seems fine to me.

**Comment by dmatetelki** [comment]
@philipseidel can you rebase your PR and do the from `memcached` to `nobody` change ?

**Comment by philipseidel** [comment]
@dmatetelki all set.

**Comment by dridi** [comment]
Merged manually in 4c4d818ecdf8d87db30e5f26511a1c682b31eb1c, thanks again!

**Pull request closed without merging**
